#https://opentdb.com/
#the below questions I have taken from the website above api
# question_data = [
#     {"type": "boolean",
#      "difficulty": "easy",
#      "category": "Science: Computers",
#      "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "A Mac is not a PC",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
#      "incorrect_answers": ["False"]}]

question_data = [
{"question": "A slug's blood is green.", "correct_answer": "True"},
{"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
{"question": "Approximately one quarter of human bones are in the feet.", "correct_answer": "True"},
{"question": "The total surface area of a human lungs is the size of a football pitch.", "correct_answer": "True"},
{"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "correct_answer": "True"},
{"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "correct_answer": "False"},
{"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
{"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
{"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
{"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
{"question": "No piece of square dry paper can be folded in half more than 7 times.", "correct_answer": "False"},
{"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"}
]
